steps:
  - label: ":one:"
    command: echo "Step 1 Successful!"
  - label: ":two:"
    command: echo "Step 2 Successful!"
  - label: ":three:"
    command: echo "Step 3 Successful!"
  - label: ":green_heart:"
    command: echo "Build Finished!"
